### ISSUE TITLE
Clarification of the setup you use?

### ISSUE THREAD

**Issue by torian257x** [faebeee/react-component-creator-plugin#4]
love the plugin!

How do you make the _<ComponentName>.scss files compile along with the component?

e.g. what are you using in conjunction with it?

**Comment by faebeee** [comment]
Hi and thanks

They are getting compiled seperatedly (seperation of concern)
I use [sass-globi](https://www.npmjs.com/package/gulp-sass-globi) to import all scss files recursively in my project and create one single css file.

I'm running with gulp to compile my js with webpack and my scss with node/dart sass

Hope this helps. 
I'm currently working an a project which is a private repo and I'm planning to publish it at the end of may. There I'm using exactly that setup. I'll send it to you when it's public.

**Comment by torian257x** [comment]
thanks @faebeee I highly appreciate your comment. I want to give you my opinion though, and only my opinion. There is a reason recent changes to bootstrap, and newcomers like tailwindcss and vue are so popular

for me personally it would be better to have the file be compiled into some css module that gets imported or something like that I think. E.g. if you delete the component, you are safe to assume that nothing else gets changed

**Comment by faebeee** [comment]
I understand. I think everyone has It's own opinion about seperation and that is totally fine. If you like to import the scss in your component and let webpack handle that it's fine and you can edit the template. In the settings of the project, you can choose which template should be used for which file. There you can link your own file where you import the scss file directly in the component.

**Comment by faebeee** [comment]
@Jossnaz here is the project. It's written in Vue but the setup is pretty much the same
https://github.com/faebeee/lighthouse-dashboard

**Comment by torian257x** [comment]
@faebeee that app looks very fine! and none trivial as well. Would be interesting to know how you measure SEO and the other indicators, and in what cases it doesnt work.

Bisch abr nid schwyzr odr öppe scho

**Comment by faebeee** [comment]
HI @Jossnaz jep also from switzerland ;)

The app uses lighthouse under the hood. I get the results from that module and persist them in a mongodb. So all the magic to gather the data comes from [lighthouse](https://developers.google.com/web/tools/lighthouse)
